language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"

before_install:
  - sudo apt update -y
  - sudo apt-get -y install lua5.1 luarocks
  - sudo luarocks install luacheck

install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-test.txt

script:
  - make lint
